name: todoapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true


flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png
  remove_alpha_ios: true
  adaptive_icon_background: "#0F1117"
  adaptive_icon_foreground: assets/images/logo.png
  min_sdk_android: 21

 